defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: cuda_pytorch_llama_compile

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  device: cuda
  device_ids: 4
  no_weights: false  # Set to true to load random weights
  torch_dtype: bfloat16
  model: meta-llama/Llama-3.1-8B-Instruct

scenario:
  memory: true
  latency: true
  input_shapes:
    batch_size: 1
    sequence_length: 64
  generate_kwargs:
    max_new_tokens: 64
    min_new_tokens: 64
    do_sample: false
    num_beams: 1
    cache_implementation: static