defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: llama_gptq_2bit

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  quantization_scheme: gptq
  quantization_config:
      bits: 2
      use_exllama: false
      dataset: "c4"  # Calibration dataset; can use your own data
  model: meta-llama/Llama-3.1-8B-Instruct

scenario:
  memory: true
  latency: true
  input_shapes:
    batch_size: 1
    sequence_length: 64
  generate_kwargs:
    max_new_tokens: 64
    min_new_tokens: 64
    do_sample: false
    num_beams: 1