defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: llama70b_bnb_8bit

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  model: "meta-llama/Llama-3.1-70B-Instruct"
  quantization_scheme: bnb
  quantization_config:
    load_in_8bit: true
  torch_dtype: float16

scenario:
  memory: true
  latency: true
  input_shapes:
    batch_size: 1
    sequence_length: 64
  generate_kwargs:
    max_new_tokens: 64
    min_new_tokens: 64
    do_sample: false
    num_beams: 1