defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: llama70b_vptq_compile_static

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  model: VPTQ-community/Meta-Llama-3.1-70B-Instruct-v16-k65536-65536-woft
  torch_dtype: bfloat16

scenario:
  memory: true
  latency: true
  input_shapes:
    batch_size: 1
    sequence_length: 64
  generate_kwargs:
    max_new_tokens: 64
    min_new_tokens: 64
    do_sample: false
    num_beams: 1
    cache_implementation: static