defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: llama8b_compressedfp8

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  model: neuralmagic/Meta-Llama-3.1-8B-Instruct-FP8
  torch_dtype: bfloat16

scenario:
  memory: true
  latency: true
  input_shapes:
    batch_size: 1
    sequence_length: 64
  generate_kwargs:
    max_new_tokens: 64
    min_new_tokens: 64
    do_sample: false
    num_beams: 1