defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_
  - _torch_compile_

name: llama70b_quanto_int8wo_compile

launcher:
  device_isolation: true
  device_isolation_action: warn

backend:
  quantization_scheme: quanto
  quantization_config:
    weights: int8
  model: meta-llama/Llama-3.1-70B-Instruct
  torch_dtype: bfloat16

scenario:
  memory: true
  latency: true
  input_shapes:
    batch_size: 1
    sequence_length: 64
  generate_kwargs:
    max_new_tokens: 64
    min_new_tokens: 64
    do_sample: false
    num_beams: 1